version: "3.7"
services:
    app:
      build:
          args:
            user: nologo
            uid: 1000
          context: ./
          dockerfile: ./docker-compose/php-fpm/Dockerfile
      image: web-front-docker
      container_name: web-front
      restart: unless-stopped
      working_dir: /var/www/
      volumes:
          - ./:/var/www
      networks:
          - web-ui
    nginx:
      image: nginx:alpine
      container_name: web-front-nginx
      restart: unless-stopped
      ports:
          - 8010:80
      volumes:
          - ./:/var/www
          - ./docker-compose/nginx:/etc/nginx/conf.d
      networks:
          - web-ui
    #Mysl Service:
    db:
      image: mysql:8
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: web_shop
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: root
        MYSQL_USER: nologo
      networks:
        - web-ui

networks:
  web-ui:
    driver: bridge